### ISSUE TITLE
MVA & Officer Requiring Assistance: STP not supported

### ISSUE THREAD

**Issue by ziipzaaapM16A4** [ziipzaaapM16A4/Default-AiCallouts-Pack#6]
There is a feature in MVA & Officer Requiring Assistance which requires the player to frisk the suspect. 
But currently only LSPDFR frisks are supported. 
If StopThePed is used there is no lspdfr frisk task the player could do.

**Comment by RelaperCrystal** [comment]
There is an event in STP that occurs when a ped has been frisked.

**Comment by ziipzaaapM16A4** [comment]
Correct. I am already working on a compatibility

**Comment by ziipzaaapM16A4** [comment]
e577a578eaedf6ccd268ba44cfd122bc1879f33a

[Fix] missing stp integration for frisk task
