### ISSUE TITLE
Critical Crash caused AAIC

### ISSUE THREAD

**Issue by wanou067** [ziipzaaapM16A4/Default-AiCallouts-Pack#7]
Hello,
I'm creating this issue because I noticed that AAIC caused LSPDFR to crash when I died (not during a callout)

Theses are the logs, can you please have a look ?

[logs on pastebin](https://pastebin.com/6DF2bvky)

Thanks you in advance

**Comment by wanou067** [comment]
Hi again, this is an other critical crash, that instantly fully crashed the game
https://pastebin.com/SqyxT7vv

**Comment by ziipzaaapM16A4** [comment]
I would need the full log to determin which version you are using
